name: build-openwrt-lxd-images
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  matrix-setup:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          json_versions=$(sed -r 's/""/","/g' <<< $(curl https://downloads.openwrt.org/releases/ |  grep -zPo -- '"\d+.\d+.\d+\/"|"\d+.\d+.\d+-rc\d\/"' | tr -d '\0') | (echo {\"versions\":[ && cat && echo ]}) | jq -c .)
          echo "matrix=$(sed -r 's/"/\\"/g' <<< $json_versions)" >> "$GITHUB_OUTPUT"

  build-openwrt-lxd-images:
    needs: matrix-setup
    runs-on: ubuntu-22.04
    steps:
      - run: echo ${{ needs.set-matrix.outputs.matrix }}
