name: build-openwrt-lxd-images
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  matrix-setup:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          json_versions=$(sed -r 's/""/","/g' <<< $(curl https://downloads.openwrt.org/releases/ |  grep -zPo -- '"\d+.\d+.\d+\/"|"\d+.\d+.\d+-rc\d\/"' | tr -d '\0') | (echo {\"versions\":[ && cat && echo ]}) | jq .)
          echo "matrix=$json_versions" >> "GITHUB_OUTPUT"

  build-openwrt-lxd-images:
    runs-on: ubuntu-22.04
    strategy:
      matrix: ${{fromJson(needs.matrix-setup.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.versions }}
