name: build-openwrt-lxd-images
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  matrix-setup:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          #json_versions=$(sed -r 's/""/","/g' <<< $(curl https://downloads.openwrt.org/releases/ |  grep -zPo -- '"\d+.\d+.\d+\/"|"\d+.\d+.\d+-rc\d\/"' | | head -1 tr -d '\0' ) | (echo {\"versions\":[ && cat && echo ]}) | jq -c .)
          echo "matrix={\"versions:\":[\"22.03.5\"]}" >> "$GITHUB_OUTPUT"

  build-openwrt-lxd-images:
    needs: matrix-setup
    runs-on: ubuntu-22.04
    strategy:
      matrix: ${{fromJson(needs.matrix-setup.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for Tag
        run: |
          if git show-ref --tags --verify --quiet "refs/tags/${{ matrix.versions }}"; then
            echo "Tag ${{ matrix.versions }} exists"
          else
            echo "Tag ${{ matrix.versions }} does not exist"
          fi
